### ISSUE TITLE
Cely Locksmith error

### ISSUE THREAD

**Issue by doronkatz** [initFabian/Cely#32]
Hi folks, running Cely, I get the following error on iOS 12:

`error: The operation couldn’t be completed. (Cely.LocksmithError error 7.)`

Im following the same example as in the docs, and im not sure what the issues is.

**Comment by initFabian** [comment]
Hey @doronkatz, 

This is an issue within Locksmith. To my knowledge, it shouldn't cause any crashes. Is your application Crashing?

**Comment by alextall** [comment]
@doronkatz I found that LocksmithError 7 indicates that an attempt was made to read/modify/delete a value that was not found in the keychain.

**Comment by initFabian** [comment]
resolved with #37 with the removal of Locksmith dependency 🙃
