### ISSUE TITLE
Could not build Objective-C module 'Cely'

### ISSUE THREAD

**Issue by thunpisit** [initFabian/Cely#33]
I'm working on Xcode 10.2.1 and after install through CocoaPod and import Cely I got an error `Could not build Objective-C module 'Cely'`

**Comment by alextall** [comment]
Thanks for the report. I should be able to take a look at this today.

**Comment by alextall** [comment]
@thunpisit What version of Swift are you targeting?

**Comment by thunpisit** [comment]
I'm using Swift 5

**Comment by initFabian** [comment]
resolved with #35
